# -*- coding: utf-8 -*-
"""Salinan bismillah

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhjBN6di0xHLZM-7djaIcc3EIUQArVIW

# **Automate**
"""

import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

def preprocess(input_path, output_path):

    df = pd.read_csv(input_path)

    # Missing values
    for col in df.columns:

        if df[col].dtype == 'object':
            df[col].fillna(df[col].mode()[0], inplace=True)

        else:
            df[col].fillna(df[col].median(), inplace=True)

    # Encoding
    le = LabelEncoder()

    for col in df.select_dtypes(include='object').columns:
        df[col] = le.fit_transform(df[col])

    # Scaling
    X = df.drop("Loan_Status", axis=1)
    y = df["Loan_Status"]

    scaler = StandardScaler()

    X_scaled = scaler.fit_transform(X)

    processed = pd.DataFrame(X_scaled, columns=X.columns)

    processed["Loan_Status"] = y

    processed.to_csv(output_path, index=False)

    print("Preprocessing berhasil!")

if __name__ == "__main__":

    preprocess(
        "loan.csv",
        "loan_preprocessed.csv"
    )