# -*- coding: utf-8 -*-
"""Salinan bismillah

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhjBN6di0xHLZM-7djaIcc3EIUQArVIW

# **Automate**
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load dataset
df = pd.read_csv("loan.csv")

# =========================
# HANDLE MISSING VALUES
# =========================

# Kolom numerik
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Kolom kategorikal
cat_cols = df.select_dtypes(include=['object']).columns

# Isi missing numerik dengan median
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Isi missing kategorikal dengan modus
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# =========================
# ENCODING
# =========================

le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

# =========================
# HAPUS DUPLIKAT
# =========================

df.drop_duplicates(inplace=True)

# =========================
# SAVE PREPROCESSING
# =========================

df.to_csv("preprocessing/loan_preprocessing.csv", index=False)

print("Preprocessing selesai!")